# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 04:41
from __future__ import unicode_literals

import amzpay.models.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_title', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=50)),
                ('merchant_id', models.CharField(max_length=200)),
                ('mws_access_key', models.CharField(max_length=200)),
                ('mws_secret_key', models.CharField(max_length=200)),
                ('app_title', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=50)),
                ('app_id', models.CharField(max_length=200, unique=True)),
                ('client_id', models.CharField(max_length=200, unique=True)),
                ('client_secret', models.CharField(max_length=200)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('region', models.CharField(default='na', max_length=50)),
                ('currency_code', models.CharField(default='JPY', max_length=50)),
                ('sandbox', models.BooleanField(default=True)),
                ('button_type', models.CharField(choices=[('LwA', 'Login with Amazon'), ('PwA', 'Pay with Amazon')], default='LwA', max_length=20)),
                ('button_color', models.CharField(choices=[('Gold', 'Gold'), ('LightGray', 'Light Gray'), ('DarkGray', 'Dark Gray')], default='Gold', max_length=20)),
                ('button_size', models.CharField(choices=[('small', 'Small Button Size'), ('medium', 'Medium Button Size'), ('large', 'Large Button Size'), ('x-large', 'XLarge Button Size')], default='small', max_length=20)),
                ('auth_scope', models.TextField(blank=True, default=None, null=True)),
                ('auth_popup', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Amazon Pay Client',
                'verbose_name_plural': 'Amazon Pay Clients',
            },
            bases=(models.Model, amzpay.models.methods.Client),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Pay Scope',
                'verbose_name_plural': 'Amazon Pay Scopes',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='scope_choices',
            field=models.ManyToManyField(to='amzpay.Scope'),
        ),
    ]
