# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_title', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=50)),
                ('merchant_id', models.CharField(max_length=200)),
                ('mws_access_key', models.CharField(max_length=200)),
                ('mws_secret_key', models.CharField(max_length=200)),
                ('app_title', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=50)),
                ('app_id', models.CharField(max_length=200, unique=True)),
                ('client_id', models.CharField(max_length=200, unique=True)),
                ('client_secret', models.CharField(max_length=200)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('region', models.CharField(default='na', max_length=50)),
                ('currency_code', models.CharField(default='JPY', max_length=50)),
                ('sandbox', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Amazon Pay Client',
                'verbose_name_plural': 'Amazon Pay Clients',
            },
        ),
    ]
