# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 09:11
from __future__ import unicode_literals

import amzpay.models.methods
import amzpay.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('amzpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_number', models.CharField(max_length=32, unique=True, verbose_name='Application Authorization Number(ID)')),
                ('authorization_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Amazon Pay Authorization ID')),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Amazon Pay Auth State')),
                ('reason', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Amazon Pay Auth State Reason')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Authorization Amount')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Authroization Fee')),
                ('captured_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Captured Amount')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Seller Authorization Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Amazon Pay Authorization',
                'verbose_name_plural': 'Amazon Pay Authorizations',
            },
            bases=(models.Model, amzpay.models.methods.PayAuth, amzpay.models.PayMixin),
        ),
        migrations.CreateModel(
            name='PayCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('request', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Amazon Pay Call',
                'verbose_name_plural': 'Amazon Pay Calls',
            },
            bases=(models.Model, amzpay.models.methods.PayCall),
        ),
        migrations.CreateModel(
            name='PayCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_number', models.CharField(max_length=32, unique=True, verbose_name='Application Capture Number(ID)')),
                ('capture_id', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='Amazon Pay Capture ID')),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Amazon Pay Capture State')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Capture Amount')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Capture Fee')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Refund Amount')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Seller Capture Note')),
                ('descriptor', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Capture Soft Descriptor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payauth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amzpay.PayAuth')),
            ],
            options={
                'verbose_name': 'Amazon Pay Capture',
                'verbose_name_plural': 'Amazon Pay Captures',
            },
            bases=(models.Model, amzpay.models.methods.PayCapture, amzpay.models.PayMixin),
        ),
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Seller Order ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Amount')),
                ('customer', models.TextField(blank=True, default=None, null=True, verbose_name='Customer Information')),
                ('order_reference_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Amazon Pay Order Reference ID')),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Amazon Pay Order State')),
                ('reason', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Amazon Pay Order State Reason')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Amazon Pay Order State Reason Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Amazon Pay Order',
                'verbose_name_plural': 'Amazon Pay Orders',
            },
            bases=(models.Model, amzpay.models.methods.PayOrder, amzpay.models.PayMixin),
        ),
        migrations.CreateModel(
            name='PayRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=32, unique=True, verbose_name='Application Refund Number(ID)')),
                ('refund_id', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='Amazon Pay Refund ID')),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Amazon Pay Refund State')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Refund Amount')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Refund Fee')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Seller Refund Note')),
                ('descriptor', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Refund Soft Descriptor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paycapture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amzpay.PayCapture')),
            ],
            options={
                'verbose_name': 'Amazon Pay Refund',
                'verbose_name_plural': 'Amazon Pay Refunds',
            },
            bases=(models.Model, amzpay.models.methods.PayRefund, amzpay.models.PayMixin),
        ),
        migrations.AddField(
            model_name='client',
            name='handle_throttle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='mws_auth_token',
            field=models.CharField(default='1', max_length=200, verbose_name='MWS Auth Token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('uk', 'mws-eu.amazonservices.com'), ('de', 'mws-eu.amazonservices.com'), ('eu', 'mws-eu.amazonservices.com'), ('us', 'mws.amazonservices.com'), ('na', 'mws.amazonservices.com'), ('jp', 'mws.amazonservices.jp')], default='ja', max_length=50, verbose_name='MWS Endpoint Region'),
        ),
        migrations.AddField(
            model_name='payorder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amzpay.Client'),
        ),
        migrations.AddField(
            model_name='payorder',
            name='order_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='payorder',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='payauth',
            name='payorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amzpay.PayOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='payorder',
            unique_together=set([('order_content_type', 'order_object_id')]),
        ),
    ]
